=== rmorbach/SIGMA/public/xml/map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<mp:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:mp="http://www.w3.org/2001/XMLSchema">
  <mp:element name="map">
    <mp:complexType>
      <mp:sequence>
        <mp:element name="to">
          <mp:complexType>
            <mp:sequence>
              <mp:element type="mp:string" name="protocol"/>
              <mp:element name="command" maxOccurs="unbounded" minOccurs="0">
                <mp:complexType>
                  <mp:sequence>
                    <mp:element type="mp:string" name="from"/>
                    <mp:element type="mp:string" name="equal"/>
                    <mp:element name="options" minOccurs="0">
                      <mp:complexType>
                        <mp:sequence>
                          <mp:element name="command" maxOccurs="unbounded" minOccurs="0">
                            <mp:complexType>
                              <mp:sequence>
                                <mp:element type="mp:string" name="from"/>
                                <mp:element type="mp:byte" name="equal"/>
                              </mp:sequence>
                            </mp:complexType>
                          </mp:element>
                        </mp:sequence>
                      </mp:complexType>
                    </mp:element>
                  </mp:sequence>
                </mp:complexType>
              </mp:element>
            </mp:sequence>
          </mp:complexType>
        </mp:element>
      </mp:sequence>
    </mp:complexType>
  </mp:element>
</mp:schema>

=== rmorbach/SIGMA/public/xml/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="map.xsd">
	<to>
		<protocol>ZIGBEE</protocol>
		<command>
			<from>GETSTATUS</from>
			<equal>AT</equal>
		</command>		
		<command>
			<from>GETNETID</from>
			<equal>ATID</equal>
		</command>		
		<command>
			<from>GETHIGHNUMBER</from>
			<equal>ATSH</equal>
		</command>		
		<command>
			<from>GETLOWNUMBER</from>
			<equal>ATLH</equal>
		</command>		
		<command>
			<from>EXITCOMMANDAD</from>
			<equal>ATCN</equal>
		</command>		
		<command>
			<from>SAVEEDITIONS</from>
			<equal>ATWR</equal>
		</command>		
		<command>
			<from>GETNETADDRESS</from>
			<equal>ATMY</equal>
		</command>		
		<command>
			<from>GETNUMCHILDRENS</from>
			<equal>ATNC</equal>
		</command>		
		<command>
			<from>GETNAMEDEVICE</from>
			<equal>ATNI</equal>
		</command>		
		<command>
			<from>MESSAGEAGREGATIONTIME</from>
			<equal>ATAR</equal>
		</command>		
		<command>
			<from>GET64NETID</from>
			<equal>ATOP</equal>
		</command>		
		<command>
			<from>GETMAXBROADHOP</from>
			<equal>ATNH</equal>
		</command>		
		<command>
			<from>ENABLEEENCRYPTION</from>
			<equal>ATEE</equal>
			<options>
				<command>
					<from>ENABLE</from>
					<equal>1</equal>
				</command>
				<command>
					<from>DISABLE</from>
					<equal>0</equal>
				</command>
			</options>
		</command>		
		<command>
			<from>OPTIONSENCRYPTION</from>
			<equal>ATEO</equal>
		</command>		
		<command>
			<from>SETNETENCRYPTION</from>
			<equal>ATNK</equal>
		</command>		
		<command>
			<from>SETLINKENCRYPTION</from>
			<equal>ATKY</equal>
		</command>	
		<command>
			<from>SUPPLYMODE</from>
			<equal>ATPM</equal>
			<options>
				<command>
					<from>ENABLE</from>
					<equal>1</equal>
				</command>
				<command>
					<from>DISABLE</from>
					<equal>0</equal>
				</command>
			</options>
		</command>
		<command>
			<from>GETSIGNALSTRENGTH</from>
			<equal>ATDB</equal>
		</command>
		<command>
			<from>SERIALDATARATE</from>
			<equal>ATBD</equal>
		</command>
		<command>
			<from>IOSAMPLERATE</from>
			<equal>ATIR</equal>
		</command>
		<command>
			<from>GETSUPPLYVOLTAGE</from>
			<equal>AT%V</equal>
		</command>
		<command>
			<from>GETLASTJOININFO</from>
			<equal>ATAI</equal>
		</command>
		<command>
			<from>SLEEPMODE</from>
			<equal>ATSM</equal>
			<options>
				<command>
					<from>ENABLE</from>
					<equal>1</equal>
				</command>
				<command>
					<from>DISABLE</from>
					<equal>0</equal>
				</command>
				<command>
					<from>ENABLECY</from>
					<equal>4</equal>
				</command>
				<command>
					<from>ENABLECYWAKE</from>
					<equal>5</equal>
				</command>
			</options>
		</command>
		<command>
			<from>SLEEPPERIOD</from>
			<equal>ATSN</equal>
		</command>
		<command>
			<from>SEACHRATEENDDEVICE</from>
			<equal>ATPO</equal>
		</command>
		<command>
			<from>RESTOREDEFAULT</from>
			<equal>ATRE</equal>
		</command>
		<command>
			<from>RESTORENET</from>
			<equal>ATNR</equal>
		</command>
		<command>
			<from>NODEDISCOVERY</from>
			<equal>ATND</equal>
		</command>			
	</to>	
</map>
